source 'https://rubygems.org'
ruby '2.5.1'

gem 'rspec', '~> 3.5'
gem 'capybara'
gem 'capybara-screenshot'
gem 'cucumber'
gem 'dotenv'
gem 'selenium-webdriver'
gem 'site_prism', '2.16'
gem "parallel_tests"
gem 'syntax'
gem 'byebug'
gem 'chunky_png', '1.3.7'
gem 'imatcher', '0.1.5'
gem 'os'